version: "3"

services:
  main:
    build: .
    restart: always
    network_mode: host
    volumes:
      - ./logs:/logs
    command: sh -c 'chmod 777 /logs && /app/passer --port 8888 --max_throughput 80 | /app/rotator --log_path /logs/passer.log --max_size 100'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
