version: "3"

services:
  main:
    restart: always
    build: .
    network_mode: host
    volumes:
      - ./logs:/logs
    command: sh -c 'chmod 777 /logs && /app/passer --port 8888 --max_throughput 80 | /app/rotator --log_path /logs/passer.log --max_size 100'
